# Generated by Django 5.1 on 2024-08-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemstripe', '0005_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='rate',
        ),
        migrations.AddField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tax',
            name='jurisdiction',
            field=models.CharField(default='RU', max_length=255),
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
