# Generated by Django 5.1 on 2024-08-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemstripe', '0006_remove_tax_rate_tax_inclusive_tax_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
