# Generated by Django 5.1 on 2024-08-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemstripe', '0008_item_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
    ]
